### ISSUE TITLE
Mauch Metric

### ISSUE THREAD

**Issue by simonefrancia** [f90/jamendolyrics#3]
Hi, 
where can I find a definition of mauch metric?
Thanks

**Comment by f90** [comment]
Hey, its defined in equation (2) in the paper
Integrating additional chord information into hmm-based lyrics-to-audio alignment 
accessible here
https://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.310.799

Also quite easy to understand how it's calculated based on my code here
https://github.com/f90/jamendolyrics/blob/bf9bb57d9bdc44500c2fc0e1544fc836566875c7/Evaluate.py#L40

Does that help?

**Comment by simonefrancia** [comment]
Thank you very much.
So if I understood well, mauch(0.1) it's the percentage of alignments that have absolute deviation under a certain value of tolerance, in this case 0.1. 
Am I right? :)

**Comment by f90** [comment]
Hey, yes that is correct. With the one detail that you don't calculate the percentage over all words in the dataset at once, but rather for each song individually, and then you average those song-wise percentages over the whole dataset. This means an error in a shorter song has a higher influence than an error in a longer song that contains more words. One could easily change this to calculate the percentage over the whole dataset, but then that is technically a different metric.

**Comment by simonefrancia** [comment]
Very clear, thank you.
I have some other questions. 
1. Are there other metrics that can be useful to understand the performance of an aligner?
(Other than these https://github.com/f90/jamendolyrics/blob/bf9bb57d9bdc44500c2fc0e1544fc836566875c7/Evaluate.py#L117
)
2. Which metric is more representative and is the reference for choosing which algorithm is the state of the art for alignments? ( in the case only one is sufficient ) 
Thanks a lot!

**Comment by f90** [comment]
1. I think the metrics computed in the code are pretty exhaustive overall. But it's easy to create new ones focussing on specific aspects, e.g. the maximum amount of misalignment overall/per song to look at the worst-case, etc. Not a metric, but one can also look at the histogram of errors that is ploted in this code to get more detailed understanding of the errors and model behaviour.

2. The most-used metrics are the Mauch one, the mean absolute error (``mean_AE`` in the code), and the percentage of correct alignments (``mean_perc`` in the code). There is no one metric that is used as standard everywhere at the moment. I think this is because these metrics cover different aspects of the model's errors - Mauch just cares about whether a word is aligned correctly (within a tolerance window) or not, while the mean AE punishes large errors much more since it takes into account the amount of misalignment.

**Comment by simonefrancia** [comment]
Very exhaustive, very clear! 
Thank you very much!
